{"name": "test_verify_login_problem_user", "status": "passed", "description": "Verify that the user is able to Login with problem user", "attachments": [{"name": "log", "source": "58436f8f-b1d3-4c6a-a44f-2e9bfb5ff7b4-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "3c1f5b20-eb8e-43dd-b80e-e0e692539999-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "9e7f4684-0ac3-4115-8dd2-3cdc6bb929b9-attachment.txt", "type": "text/plain"}], "start": 1657042831500, "stop": 1657042836163, "uuid": "c8f050f4-cb92-4543-bae7-6882236afca3", "historyId": "c9474a61d0976d42351f899f54d38228", "testCaseId": "f8008a82df277cd9d2f7aad7af2a50b0", "fullName": "testCases.test_login.Test_Login#test_verify_login_problem_user", "labels": [{"name": "parentSuite", "value": "testCases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_Login"}, {"name": "host", "value": "Muhammads-MacBook-Pro.local"}, {"name": "thread", "value": "56893-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCases.test_login"}]}